server:
  port: 8082                # transform-rpc 服务监听的 gRPC 端口

snowflake:
  start_time: "2026-01-01"  # 起始时间
  machine_id: 1             # 当前机器编号

mysql:
  dsn: "root:123456@tcp(127.0.0.1:3306)/shorturl?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: "123456"
  db: 0
  expiration_hours: 24