// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/ai/v1/ai.proto

package aiV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ----------------- 安全检测 DTO -----------------
type CheckURLSafetyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckURLSafetyRequest) Reset() {
	*x = CheckURLSafetyRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLSafetyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLSafetyRequest) ProtoMessage() {}

func (x *CheckURLSafetyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLSafetyRequest.ProtoReflect.Descriptor instead.
func (*CheckURLSafetyRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *CheckURLSafetyRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CheckURLSafetyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSafe        bool                   `protobuf:"varint,1,opt,name=is_safe,json=isSafe,proto3" json:"is_safe,omitempty"`                  // 是否安全（true=安全放行，false=恶意拦截）
	RiskLevel     string                 `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`          // 风险等级：SAFE / LOW / MEDIUM / HIGH
	RiskCategory  string                 `protobuf:"bytes,3,opt,name=risk_category,json=riskCategory,proto3" json:"risk_category,omitempty"` // 风险类型（如：钓鱼网站、仿冒官网、电信诈骗、色情暴力）
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                 // 大模型给出的详细风险研判原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckURLSafetyResponse) Reset() {
	*x = CheckURLSafetyResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckURLSafetyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckURLSafetyResponse) ProtoMessage() {}

func (x *CheckURLSafetyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckURLSafetyResponse.ProtoReflect.Descriptor instead.
func (*CheckURLSafetyResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *CheckURLSafetyResponse) GetIsSafe() bool {
	if x != nil {
		return x.IsSafe
	}
	return false
}

func (x *CheckURLSafetyResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *CheckURLSafetyResponse) GetRiskCategory() string {
	if x != nil {
		return x.RiskCategory
	}
	return ""
}

func (x *CheckURLSafetyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ----------------- 网页摘要 DTO -----------------
type SummarizeURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeURLRequest) Reset() {
	*x = SummarizeURLRequest{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeURLRequest) ProtoMessage() {}

func (x *SummarizeURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeURLRequest.ProtoReflect.Descriptor instead.
func (*SummarizeURLRequest) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *SummarizeURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SummarizeURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`     // 网页标题
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // 核心内容摘要（100字以内）
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`       // 网页关键词标签
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeURLResponse) Reset() {
	*x = SummarizeURLResponse{}
	mi := &file_api_ai_v1_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeURLResponse) ProtoMessage() {}

func (x *SummarizeURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ai_v1_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeURLResponse.ProtoReflect.Descriptor instead.
func (*SummarizeURLResponse) Descriptor() ([]byte, []int) {
	return file_api_ai_v1_ai_proto_rawDescGZIP(), []int{3}
}

func (x *SummarizeURLResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SummarizeURLResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *SummarizeURLResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_api_ai_v1_ai_proto protoreflect.FileDescriptor

const file_api_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x12api/ai/v1/ai.proto\x12\x05ai.v1\")\n" +
	"\x15CheckURLSafetyRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8d\x01\n" +
	"\x16CheckURLSafetyResponse\x12\x17\n" +
	"\ais_safe\x18\x01 \x01(\bR\x06isSafe\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12#\n" +
	"\rrisk_category\x18\x03 \x01(\tR\friskCategory\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"'\n" +
	"\x13SummarizeURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Z\n" +
	"\x14SummarizeURLResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags2\xa3\x01\n" +
	"\tAIService\x12M\n" +
	"\x0eCheckURLSafety\x12\x1c.ai.v1.CheckURLSafetyRequest\x1a\x1d.ai.v1.CheckURLSafetyResponse\x12G\n" +
	"\fSummarizeURL\x12\x1a.ai.v1.SummarizeURLRequest\x1a\x1b.ai.v1.SummarizeURLResponseB\x19Z\x17shorturl/api/ai/v1;aiV1b\x06proto3"

var (
	file_api_ai_v1_ai_proto_rawDescOnce sync.Once
	file_api_ai_v1_ai_proto_rawDescData []byte
)

func file_api_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_api_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_api_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ai_v1_ai_proto_rawDesc), len(file_api_ai_v1_ai_proto_rawDesc)))
	})
	return file_api_ai_v1_ai_proto_rawDescData
}

var file_api_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_ai_v1_ai_proto_goTypes = []any{
	(*CheckURLSafetyRequest)(nil),  // 0: ai.v1.CheckURLSafetyRequest
	(*CheckURLSafetyResponse)(nil), // 1: ai.v1.CheckURLSafetyResponse
	(*SummarizeURLRequest)(nil),    // 2: ai.v1.SummarizeURLRequest
	(*SummarizeURLResponse)(nil),   // 3: ai.v1.SummarizeURLResponse
}
var file_api_ai_v1_ai_proto_depIdxs = []int32{
	0, // 0: ai.v1.AIService.CheckURLSafety:input_type -> ai.v1.CheckURLSafetyRequest
	2, // 1: ai.v1.AIService.SummarizeURL:input_type -> ai.v1.SummarizeURLRequest
	1, // 2: ai.v1.AIService.CheckURLSafety:output_type -> ai.v1.CheckURLSafetyResponse
	3, // 3: ai.v1.AIService.SummarizeURL:output_type -> ai.v1.SummarizeURLResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ai_v1_ai_proto_init() }
func file_api_ai_v1_ai_proto_init() {
	if File_api_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ai_v1_ai_proto_rawDesc), len(file_api_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_api_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_api_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_api_ai_v1_ai_proto = out.File
	file_api_ai_v1_ai_proto_goTypes = nil
	file_api_ai_v1_ai_proto_depIdxs = nil
}
