// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/ai/v1/ai.proto

package aiV1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_CheckURLSafety_FullMethodName = "/ai.v1.AIService/CheckURLSafety"
	AIService_SummarizeURL_FullMethodName   = "/ai.v1.AIService/SummarizeURL"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI 智能微服务接口定义
type AIServiceClient interface {
	// 1. 网址安全与钓鱼风险检测
	CheckURLSafety(ctx context.Context, in *CheckURLSafetyRequest, opts ...grpc.CallOption) (*CheckURLSafetyResponse, error)
	// 2. 网页智能摘要提取
	SummarizeURL(ctx context.Context, in *SummarizeURLRequest, opts ...grpc.CallOption) (*SummarizeURLResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) CheckURLSafety(ctx context.Context, in *CheckURLSafetyRequest, opts ...grpc.CallOption) (*CheckURLSafetyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckURLSafetyResponse)
	err := c.cc.Invoke(ctx, AIService_CheckURLSafety_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SummarizeURL(ctx context.Context, in *SummarizeURLRequest, opts ...grpc.CallOption) (*SummarizeURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeURLResponse)
	err := c.cc.Invoke(ctx, AIService_SummarizeURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
//
// AI 智能微服务接口定义
type AIServiceServer interface {
	// 1. 网址安全与钓鱼风险检测
	CheckURLSafety(context.Context, *CheckURLSafetyRequest) (*CheckURLSafetyResponse, error)
	// 2. 网页智能摘要提取
	SummarizeURL(context.Context, *SummarizeURLRequest) (*SummarizeURLResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) CheckURLSafety(context.Context, *CheckURLSafetyRequest) (*CheckURLSafetyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckURLSafety not implemented")
}
func (UnimplementedAIServiceServer) SummarizeURL(context.Context, *SummarizeURLRequest) (*SummarizeURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SummarizeURL not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_CheckURLSafety_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckURLSafetyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CheckURLSafety(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CheckURLSafety_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CheckURLSafety(ctx, req.(*CheckURLSafetyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SummarizeURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SummarizeURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SummarizeURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SummarizeURL(ctx, req.(*SummarizeURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckURLSafety",
			Handler:    _AIService_CheckURLSafety_Handler,
		},
		{
			MethodName: "SummarizeURL",
			Handler:    _AIService_SummarizeURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ai/v1/ai.proto",
}
